server:
  port: 10086
  servlet:
    context-path: /chuoyue

spring:
  application:
    name: chuoyue_video_server
  datasource:
    username: root
    password: password
    url: jdbc:mysql://192.168.1.100:3306/video_surveillance?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      stat-view-servlet:
        login-username: chuoyue
        login-password: password
#  boot:
#    admin:
#      ui:
#        title: '绰约'

mybatis-plus:
  mapper-locations: classpath*:com/fuyunwang/chuoyue/**/xml/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

rabbitmq:
  address: 127.0.0.1
  port: 5672
  username: guest
  password: guest
  virtualHost: /